version: 2
orbs:
  orb-tools: circleci/orb-tools@8.27.4
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
            - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: unmock/unmock
          requires:
            - orb-tools/pack